service: sls-base
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHasingVersion: '20211221'
  memorySize: 256
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          method: GET
          path: '/hello'
