service: sls-base
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHasingVersion: '20211221'
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AWS_ACCOUNT_ID: ${self:custom.accountId}
    AWS_REGION: ${self:custom.region}

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          method: GET
          path: '/hello'

custom:
  accountId: ${aws:accountId}
  region: ${aws:region}
  bundle:
    linting: false
